### ISSUE TITLE
Node version upgrade needed

### ISSUE THREAD

**Issue by cronnelly** [clocklimited/qrgen#6]
This is running in production on Node 0.8.12. There are several newer versions in 0.8 which address important security issues. On top of that, the whole 0.8 line hasn't been supported since February 2015.

We need to get this upgraded to the latest LTS.

**Comment by jack828** [comment]
Problem solved 8 years later https://github.com/clocklimited/qrgen/commit/209789a24b60b3e4425d4dbec09f5ba2da487c7b
